title: bear.sudo.tv
application_name: SudoTV Bear
email: wm@mengw.io
description: SudoTV Bear
url: https://bear.sudo.tv
github_username: WMXPY
theme: minima
repository: SudoTV/bear.sudo.tv
plugins_dir: common/_plugins
layouts_dir: common/_layouts
data_dir: common/_data
includes_dir: common/_includes
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: WMXPY
  email: wm@mengw.io
plugins:
  - jekyll-github-metadata
exclude:
  - common/_plugins
  - common/_layouts
  - common/_data
  - common/_includes
  - "common/docs"
  - "common/LICENSE"
  - _includes
  - _layouts
  - ".vscode/"
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - _config.yml
  - ".gitignore"
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - makefile
