title: bear.sudo.tv
email: wm@mengw.io
description: SudoTV Bear With Me
url: https://bear.sudo.tv
github_username: WMXPY
theme: minima
repository: SudoTV/bear.sudo.tv
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
author:
  name: WMXPY
  email: wm@mengw.io
plugins:
  - jekyll-github-metadata
exclude:
  - .jekyll-cache/
  - docs/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - makefile
